require('dotenv').config()

module.exports = {
  env: {
    NEXT_EXAMPLE_BIGCOMMERCE_STOREFRONT_API_URL:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STOREFRONT_API_URL,
    NEXT_EXAMPLE_BIGCOMMERCE_STOREFRONT_API_TOKEN:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STOREFRONT_API_TOKEN,
    NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_URL:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_URL,
    NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_CLIENT_ID:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_CLIENT_ID,
    NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_SECRET:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_SECRET,
    NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_TOKEN:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_STORE_API_TOKEN,
    NEXT_EXAMPLE_BIGCOMMERCE_TOKEN_SECRET:
      process.env.NEXT_EXAMPLE_BIGCOMMERCE_TOKEN_SECRET,
  },
}
